### ISSUE TITLE
Bug: Upgrading to 0.13.0 from 0.12.0 fails

### ISSUE THREAD

**Issue by bebold-jhr** [lacework/terraform-aws-agentless-scanning#107]
**Describe the bug**
>  Error: Invalid resource type
│ 
│   on .terraform/modules/lacework_aws_agentless_scanning_global/main.tf line 89, in resource "lacework_external_id" "aws_iam_external_id":
│   89: resource "lacework_external_id" "aws_iam_external_id" {
│ 
│ The provider lacework/lacework does not support resource type
│ "lacework_external_id".

**Steps to reproduce**
* Deploy module using 0.12.0
* Perform terraform plan with upgrade to 0.13.0
* Lacework provider version: 1.13.3 (unchanged)

**Expected behavior**
No changes.

**Screenshots**

**Please complete the following information):**
 - Terraform Version: v1.5.5
 - Module Version v0.13.0 

Run `terraform version` to find your Terraform version.
You can find the module version by running `terraform providers` or in your terraform configuration. If developing locally you can check the `VERSION` file in the project root directory.

**Additional context**

**Comment by bebold-jhr** [comment]
Must be because of

feat: enforce External ID v2 format (https://github.com/lacework/terraform-aws-agentless-scanning/pull/97) (djmctavish)([9663c86](https://github.com/lacework/terraform-aws-agentless-scanning/commit/9663c869eb00c64da5a2cdfa07a82423cf0c4f1a))

But then I would expect this to reflect on the required provders block like this:

```hcl
required_providers {
    aws    = ">= 4.0"
    random = ">= 2.1"
    lacework = ">=1.15.0"
  }
```

**Comment by afiune** [comment]
Hey @bebold-jhr - Apologies for the inconveniences, also... You are spot on! We forgot to bump
the provider version to `>= 1.15.0` since that version is the one that added the new resource
`lacework_external_id`. https://github.com/lacework/terraform-provider-lacework/releases/tag/v1.15.0

Let me quickly fix it. 

<img src="https://media1.giphy.com/media/Rpl1sod1vCXK0L2SUN/giphy.gif"/>
