### ISSUE TITLE
Question: What is the purpose of validating on 4 chars for suffix property?

### ISSUE THREAD

**Issue by bebold-jhr** [lacework/terraform-aws-agentless-scanning#71]
I would like to know what the reason is behind the 4 chars minimum on the suffix property?
It's mostly used for names so why not just accept that it's either not set or set with anything?

**Comment by theopolis** [comment]
You are correct, my understanding is that we added this requirement to protect folks against installing it twice with the same names and receiving hard-to-debug error messages around naming conflicts.

**Comment by bebold-jhr** [comment]
I can see that setting a random suffix, if the user didn't set any, can prevent users from getting naming conflicts.
But to be honest I don't really see how setting a minimum length for the value set by the user could prevent this.
Wouldn't it make sense to just remove that? We had to work around that and add useless static noise to the name in order to bypass this restriction.

**Comment by theopolis** [comment]
Sure thing, so just to be clear, what would work for you is to remove the length restriction?

**Comment by bebold-jhr** [comment]
Yes, exactly. So I guess the whole validation block can be removed, because there is no other check in place on the suffix.
